### PR TITLE
fix: bump the blockly peer dependency in dev-tools and remove version probing

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Work on #882 Also fix https://github.com/google/blockly/pull/6204

Requires us to bump devtools to only work with v8+.

### CODE REVIEW

**Comment by maribethb** [comment]
If this requires us to update the dev-tools dependency then do that in this PR and mark this as a breaking change, then lgtm

**Review by maribethb — APPROVED** [review]

**Comment by BeksOmega** [comment]
The id generator fix was already reviewed by Aaron in #1184 No need to re-review. Just moving everything into one PR.

**Comment by maribethb** [comment]
This should be a breaking change. If someone is using blockly v7 then we would not want npm to automatically update them to this version of the plugin since it is no longer compatible. It has to be a major update so that they manually update when needed. You can probably still update the title of this PR to affect lerna's reading of the commit, but I'm not sure.

And since this would be a major version update of dev-tools I think that means we need to manually update all of the other plugins to depend on the new version because lerna won't keep them up to date after a major change is what we learned last time. So we should take extra care after the next samples release (which I won't be here next week)

**Comment by BeksOmega** [comment]
> This should be a breaking change.

Yeah :/ whoops.

> You can probably still update the title of this PR to affect lerna's reading of the commit, but I'm not sure.

Pretty sure it won't, because lerna will just be looking at the git history :/ Will revert and reapply with the correct conventional commits.

> So we should take extra care after the next samples release (which I won't be here next week)

Sounds good, made a note to myself.

**Pull request merged**
