### PR TITLE
fix(field-*): Remove unneeded `fieldRegistry.unregister` calls

### LINKED ISSUE #2194: Cleanup after deleting blocks and fields from core
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Angle, colour, and multiline input fields.

### Description

After #2162 there will be multiple pieces of code in field plugins that compensate for the blocks and fields already being installed as part of the core library. Once the fields are removed form core (https://github.com/google/blockly/issues/7226), the plugins will need to be updated.

Examples include
- In test pages, deleting blocks and generators for blocks provided by the plugin.
- In field registration functions, unregistering existing fields before registering the new ones.

### Reproduction steps

_No response_

### Stack trace

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by cpcallen**
## The basics

- [ ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details

Fixes #2194.

### Proposed Changes

Remove unneeded `fieldRegistry.unregister` calls from `plugins/field-angle`, `field-colour` and `field-multilineinput`'s register functions.

Also remove the `unregisterBlocks` test helper functions, which are no longer needed for similar reasons.

### Reason for Changes

Since `FieldAngle`, `FieldColour` and `FieldMultilineInput` are no longer in core, there's no longer any need for their corresponding plugins to unregister the built-in version.

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
I'd like to hold this change until https://github.com/google/blockly-samples/pull/2453 goes in. I actually started working on this and went sideways into https://github.com/google/blockly-samples/pull/2453 because I could not _test_ the changes in multiple plugins with the lerna commands that I expected.

**Comment by rachel-fenichel** [comment]
This PR fixes part of https://github.com/google/blockly-samples/issues/2194. I think you should also fix the other todos so we can close the issue entirely; all are marked with the issue number.

**Comment by cpcallen** [comment]
> This PR fixes part of #2194. I think you should also fix the other todos so we can close the issue entirely; all are marked with the issue number.

OK.  I did this bit unaware of the cleanup issue because it had come up in the forum as [the warnings appear to be causing developer concern](https://groups.google.com/g/blockly/c/gMr4m4reRZE).

**Comment by cpcallen** [comment]
OK, the history of this PR is pretty chaotic due to Git-fu (and more particularly GitHub-fu) shortcomings on my part, but the code is now ready for review and now deals with all all remaining instances of `2194` in samples.

**Review by rachel-fenichel — APPROVED** [review]

**Pull request merged**
