### PR TITLE
fix: Move away from using innerHTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML. Always be cautious when dealing with user input or dynamic content to prevent security risks.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @maribethb  Could You Please Review this PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @maribethb Could You Please Review this PR
Thanks

**Comment by maribethb** [comment]
Hi @Shivam7-1, this plugin was recently converted to TypeScript so this PR needs to be rebased and the change should be made against the equivalent ts file now instead. 

Also, we use conventional commits in order to generate good release notes. Could you please follow [these instructions](https://developers.google.com/blockly/guides/contribute/get-started/commits#fixing_non-conventional_commits) to use conventional commits?

**Comment by Shivam7-1** [comment]
Hi @maribethb Thanks For Reviewing 
I think I had Committed in Lastest Repo Could You Please Review Above PR again 
Reagrds

**Comment by NeilFraser** [comment]
This is actually a good change.  Though as @maribethb states, it collides with recent commits, so it needs to be rebased.  Also, instead of `.innerText`, one should (almost) always use `.textContent`.

**Comment by Shivam7-1** [comment]
Hi @maribethb I Had Done Changes Accordingly and Updated My Branch Could Please Review This PR

Thanks

**Comment by Shivam7-1** [comment]
Hi @maribethb I Had Done Changes Accordingly and Updated My Branch Could Please Review This PR

Thanks

**Comment by Shivam7-1** [comment]
Hi @maribethb Could You Please Review This PR
Thanks

**Comment by maribethb** [comment]
@NeilFraser owns this PR review now. Thanks!

**Comment by NeilFraser** [comment]
This PR is just a whitespace change.  I don't think that's what you are looking for.

**Comment by Shivam7-1** [comment]
Hi @NeilFraser Thanks For Reviewing 
As I just check the improvement which I want to done it's already done week ago 
And After Rebase the Changes is not Required 
As I checked 

Thanks

**Comment by BeksOmega** [comment]
Closing as already completed.

**Pull request closed without merging**
