### PR TITLE
feat: add JSO hooks to plus-minus blocks

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Makes the plus-minus blocks compatible with the new JSON serialization system. Should not be merged until that is in core.

Dependent on #846 for tests.

See this pull request for reference of what the hooks need to be compatible with: https://github.com/google/blockly/pull/5329

### CODE REVIEW

**Comment by BeksOmega** [comment]
This one still needs a new version of dev-tools to be released.

**Comment by alschmiedt** [comment]
Ok, I just released a new version of dev-tools with your test helpers in it.

**Comment by BeksOmega** [comment]
Ok this is now dependent on #971, but because the core release is out I was able to link the packages and test them. Everything passes locally.

**Comment by BeksOmega** [comment]
@alschmiedt this passes locally, but it looks like lerna ran into some issue

**Comment by alschmiedt** [comment]
It looks like there is still a merge conflict in the package-lock file, could you try fixing that?

**Comment by alschmiedt** [comment]
@BeksOmega is this good to go in?

**Pull request merged**
