### PR TITLE
fix: Publish types for workspace-minimap

### LINKED ISSUE #1909: Publish types for workspace-minimap
**Category**

 - Plugins
 
**Component**

workspace-minimap

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

### PR DESCRIPTION
**Pull request by kapooraryan**
## The basics

- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Closes #1909 

### Proposed Changes

1. tsconfig.json of plugin modified to add following config options to "compilerOptions":
    "declaration": true,
    "declarationMap": true,

2. Following property added next to the "main" property in package.json:
    "types": "./dist/index.d.ts"

### Reason for Changes

To publish types for the workspace-minimap plugin.

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
Looks great :D Thank you for the fix @kapooraryan !

**Comment by BeksOmega** [comment]
Ah whoops, missed that the formatting was failing. Could you:

1) Rebase on the latest master.
2) Run `npm ci` from the root of the repository.
3) Run `npm run format`.
4) Commit any changes?

If that doesn't fix it I can fix it on my end =)

**Comment by kapooraryan** [comment]
Hey @BeksOmega , I noticed a small linter warning while working on this plugin and raised the issue for the same: #2123

**Comment by kapooraryan** [comment]
> Ah whoops, missed that the formatting was failing. Could you:
> 
> 1. Rebase on the latest master.
> 2. Run `npm ci` from the root of the repository.
> 3. Run `npm run format`.
> 4. Commit any changes?
> 
> If that doesn't fix it I can fix it on my end =)

@BeksOmega Pushed a new commit to this PR regarding the same.

**Comment by BeksOmega** [comment]
@kapooraryan can you revert the changes to the theme-hackermode package-lock.json?

**Comment by kapooraryan** [comment]
> @kapooraryan can you revert the changes to the theme-hackermode package-lock.json?

Hey @BeksOmega not sure how that occurred 😅 but done.

**Comment by BeksOmega** [comment]
Thanks again for the fixes @kapooraryan :D

**Pull request merged**
