### PR TITLE
chore: update backpack-demo toolbox xml to  JSON

### PR DESCRIPTION
**Pull request by nitesh-chowdhary**
Updated examples/backpack-demo/index.js

Updated blockly toolbox xml to JSON

Rewrite the toolbox

### CODE REVIEW

**Comment by gonfunko** [comment]
Thanks for the PR and your patience - looks like conventional commits are happy this time!

Did you convert the toolbox to JSON in a different file that wasn't checked in? `toolbox` seems like it would be undefined in the current code.

**Comment by nitesh-chowdhary** [comment]
Updated examples/backpack-demo/index.js

Updated blockly toolbox xml to JSON

**Comment by nitesh-chowdhary** [comment]
I have made changes in this file.
Do i need to work on something else as well

**Comment by cpcallen** [comment]
Hi Nitesh,

I'm oncall this week and saw your message in the Blockly developers forum and followed the trail to this PR.  I believe @gonfunko is pretty busy with other work this week so I thought I'd try to answer your question.

At the moment this PR has a single commit which just changes the value of the `toolbox` option to `Blockly.inject`, but it changes it to an undefined variable `toolbox`.  You'll need to provide a definition for the value of `toolbox`; you might find it useful to look at PRs #1296 or #1330 for examples, and the new definition of `const toolbox = {…` given in each.

(The PR should also remove the entire `<xml id="toolbox">` section from `index.html` as it will no longer be needed.)

Feel free to add those changes as a separate commit, as we'll squash this PR into a single commit when it's ready.

I'll let @gonfunko re-review this PR when it's ready, but if he is not able to respond within a day or so then feel free to reassign it to me.

**Comment by nitesh-chowdhary** [comment]
I am a beginner contributor so I just made the possible changes I could. So it's my humble request to merge this PR.

**Comment by cpcallen** [comment]
Hi Nitesh!  We appreciate your enthusiasm to contribute, but we can't merge this PR as-is because doing so will cause the backpack demo to break.  You'll need to actually fix the problems I mentioned my my previous comment.

> Updated examples/backpack-demo/index.js
> Updated blockly toolbox xml to JSON
> I have made changes in this file. Do i need to work on something else as well

Have you made changes in your local branch but not yet pushed them to the Thenitesh143:master branch on GitHub?  We won't be able to see your changes until you do that.

**Comment by BeksOmega** [comment]
Hello! I'm going to go ahead and close this as stale =) But definitely feel free to reopen if you still want to contribute!

**Pull request closed without merging**
