### PR TITLE
chore: update interpreter-demo from xml to json

### LINKED ISSUE #1260: Update  interpreter-demo to use JSON toolbox definitions instead of xml
**Category**
 - Examples

**Component**

 interpreter-demo

**Is your feature request related to a problem? Please describe.**

Many of the examples and plugins use XML toolboxes instead of the new JSON API. We should have our example code use the new APIs to best model what other developers can do with Blockly.

**Describe the solution you'd like**

Update the code in blockly-samples to use the JSON toolbox API.

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

1. Learn about [defining a toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) and read about the XML format vs the JSON format.
2. In blockly-samples, navigate to the  interpreter-demo example's directory. Some examples can be started with `npm run start` and some can be opened directly by opening the `index.html` file in a browser. The README may give specific instructions, or you can look in the `package.json` to see what scripts are defined. Note you may need to run `npm install` in the example directory. Either way, open the example's demo page to observe the toolbox and its contents.
3. Write a new copy of the toolbox definition in the JSON format instead of the XML format. Where exactly it should be declared will depend on the example. It will most likely make sense to declare the toolbox definition close to the location where it is used, i.e. where `Blockly.inject` is called.
4. Refresh the demo page and make sure the toolbox looks the same as it did before. You can compare against the version in master on the [samples site](https://google.github.io/blockly-samples/) to make sure the behavior hasn't changed. Note that not all demos are published on the samples site so it may not be there.
5. Follow the rest of the instructions in the Contributing docs to verify your change and open a PR.

### PR DESCRIPTION
**Pull request by mikebarr24**
closes #1260 
The async-execution from the live [site](https://google.github.io/blockly-samples/) doesn't seem to be working.
Happy to take on any feedback on this commit :)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Thanks for the PR! What's causing the failing in async-execution, and does it happen locally for you as well as on the live site?

**Comment by mikebarr24** [comment]
> Thanks for the PR! What's causing the failing in async-execution, and does it happen locally for you as well as on the live site?

This is the output from the console. It's only happening on live so hopefully my PR should fix it. 

`Uncaught TypeError: Cannot read properties of undefined (reading 'defineBlocksWithJsonArray')
    at wait_block.js:15:16`

`block.js:207 Uncaught TypeError: Unknown block type: wait_seconds
    at Blockly.Block (block.js:207:13)
    at new Blockly.BlockSvg (block_svg.js:130:44)
    at Blockly.WorkspaceSvg.newBlock (workspace_svg.js:991:10)
    at Blockly.Xml.domToBlockHeadless_ (xml.js:874:21)
    at Blockly.Xml.applyInputTagNodes_ (xml.js:812:19)
    at Blockly.Xml.domToBlockHeadless_ (xml.js:906:15)
    at Blockly.Xml.applyNextTagNodes_ (xml.js:842:19)
    at Blockly.Xml.domToBlockHeadless_ (xml.js:908:15)
    at Blockly.Xml.domToBlock (xml.js:557:32)
    at Blockly.Xml.domToWorkspace (xml.js:432:33)`

**Comment by rachel-fenichel** [comment]
Okay, I just checked and I can also reproduce that issue locally. Reproduction steps:
- Make sure your version of `blockly-samples` is up to date
- Open `examples/interpreter-demo/async-execution.html` in a browser
- Open the console and look for errors.

`wait_block.js:15` defines the blocks with `Blockly.common.defineBlocksWithJsonArray`, but the function is exported from Blockly as `Blockly.defineBlocksWithJsonArray`. So you can fix that issue: `Blockly.common.definedBlocksWithJsonArray` -> `Blockly.defineBlocksWithJsonArray`.

While looking at this, I also found that some of the categories in the toolbox won't open or load. That's because `examples/interpreter_demo/toolbox.js` has `"blockxml": {}` in the contents array in multiple places. Please delete those lines and check that you can open all of the categories in the toolbox without console errors.

The XML -> JSON changes you made so far look good.

**Comment by mikebarr24** [comment]
@rachel-fenichel Hopefully that should be it now. I've had a bit of a play with it. Again, happy to take on any feedback :)

**Review by rachel-fenichel — APPROVED** [review]

**Pull request merged**
