### PR TITLE
feat: update block info when dropdown field matches search query

### PR DESCRIPTION
**Pull request by ludizhan**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/google/blockly-samples/issues/1940

Part 1 change to index the dropdown field merged: https://github.com/google/blockly-samples/pull/1971
This is the part 2 change.

### Proposed Changes

Updating the `BlockInfo` in `flyoutItems_` with additional `fields` information, when a dropdown field includes with the search query.

### Reason for Changes

Without the change currently when searching a dropdown field, the default is selected even though search query is matching a different dropdown option.

### Test Coverage

Tested manually.

FYI the toolbox search feature on osd branch is broken in local for me, so I tested the change on master branch:

Before (with only the part 1 change https://github.com/google/blockly-samples/pull/1971):
Screenshot 2023-10-06 at 6 16 02 PM

After:
Screenshot 2023-10-06 at 6 17 16 PM

### Documentation

No documentation impact.

### Additional Information

There is a similar PR for master branch that addresses the same issue: https://github.com/google/blockly-samples/pull/2004
Either one should work..

### CODE REVIEW

**Comment by ludizhan** [comment]
Hi @maribethb @BeksOmega can you help approve running the workflow?

**Comment by ludizhan** [comment]
Fixed the lint error and double checked that there's no additional error for `npm run lint`.

**Comment by BeksOmega** [comment]
Heya @ludizhan ! Sorry someone didn't get back to you sooner :/ Are you still interested in working on this? We recentlymerged the `osd` branch, so this will need to be rebased against `master` to go in.

**Comment by BeksOmega** [comment]
@ludizhan I'm going to go ahead and close this as stale =) But if you're still interested in working on it just let me know!

**Pull request closed without merging**
