### PR TITLE
fix: #1902 publish types for field-date

### LINKED ISSUE #1902: Publish types for field-date
**Category**

 - Plugins
 
**Component**

field-date

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

### PR DESCRIPTION
**Pull request by nikitapola**
## The basics

- [x] I [validated my changes]

### Resolves

Fixes #1902

### CODE REVIEW

**Review by johnnesky — APPROVED** [review]

**Comment by johnnesky** [comment]
Please sign the CLA! Otherwise this looks great to me, thanks!

**Comment by nikitapola** [comment]
Hi John, I actually committed and opened the PR with two separate Github accounts it seems - I signed the CLA on both accounts but it is not reflecting due to the commit & PR being opened from separate accounts.

**Comment by johnnesky** [comment]
~~Hm, you might have to recreate the commit.~~ Check the requirements in the error message: https://github.com/google/blockly-samples/pull/1960/checks?check_run_id=17051218734

**Comment by johnnesky** [comment]
In particular, it looks like the commit author is successfully signed for the CLA, but the account that created the PR isn't yet, I think all you need to do is sign it for that account. The error message says:
❌ 15d9cbe PR Opener: @nikitapola

**Comment by johnnesky** [comment]
Closing as abandoned. Let us know if you'd like to reopen the PR!

**Pull request closed without merging**
