### PR TITLE
 feat: Enable strict mode for toolbox-search

### PR DESCRIPTION
**Pull request by ayan-joshi**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

This resolves the issue #2029 

### Proposed Changes

Added the strict mode for toolbox

### Reason for Changes

Asked as the issue for new feature 

### Additional Information

As mentioned in the issue I enable the strict mode for toolbox search to end with I also searched for the errors and fixed multiple errors in the file have a look and merge it faster if you can please @BeksOmega

### CODE REVIEW

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Hello! Before I give this a review, could you:

1) Add the inline comments you deleted back in? The license is especially important to keep for legal reasons!
2) Remove the change to `examples/README.md` since that's covered by your other PR?

**Comment by ayan-joshi** [comment]
@BeksOmega made the changes

**Comment by BeksOmega** [comment]
Hello @ayan-joshi Looks like a lot of the inline comments are still missing :/ Let me know if you're still interested in working on this now that your competition is over!

**Comment by BeksOmega** [comment]
Closing this as stale. If you want to continue working on it feel free to reopen!

**Pull request closed without merging**
