### PR TITLE
Fix: Publish types for workspace-search

### LINKED ISSUE #1910: Publish types for workspace-search
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

workspace-search

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

### PR DESCRIPTION
**Pull request by Yalagach**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #1910

### CODE REVIEW

**Review by johnnesky — APPROVED** [review]

**Comment by johnnesky** [comment]
Please sign the CLA. Otherwise this looks good to me, thanks!

**Comment by debaraj-barua** [comment]
Great job @Yalagach  :)

**Comment by Yalagach** [comment]
> Great job @Yalagach :)

Thank you

**Comment by johnnesky** [comment]
The CLA check still isn't passing yet, looks like the following two accounts need to sign it:
❌ 7c40adc PR Opener: @Yalagach
❌ 7c40adc Author: <n***h​@Nakshatras-MacBook-Air.local>

If one of those accounts is unavailable you may need to recreate the commit.

**Comment by debaraj-barua** [comment]
Hi @Yalagach,

Thanks for reaching out. Looks like your gitconfig is not correctly set and your email there might be different from the one set in GitHub.


Could you try the following, and set your GitHub username and the email you use for GitHub, which you used to sign the CLA (remove the `--global` if you have different configuration for your school/work)

```sh
git config --global user.name "Your Name Here"


git config --global user.email your@email.example

```


Once these are set, recreate the commit
```sh
git commit --amend -m "Fix: Publish types for workspace-search" 

git push --force origin osd
```

Where `origin` is your fork, and `osd` is the corresponding branch.


This should ideally fix the issue.




P.S. since I am typing this on my phone, i may have made some typos, if you see anything wrong or find some issues, please DM me in Slack with the screenshot. I'll try to reply whenever it's convenient :)  Have a great weekend 🎉

**Review by debaraj-barua — COMMENTED** [review]
@Yalagach Sorry, I thought this PR just contained one commit. But looks like it has two, so you'll need to squash the changes together.

Please try this:

```sh
git reset --soft HEAD~2
```

This should remove your last two commits but keep the changes staged.

Now, you can commit it again, and force-push.

```sh
git commit -m "Fix: Publish types for workspace-search"
git push --force origin osd
```

Where origin is your fork, and osd is the corresponding branch.

This should ideally fix the issue.

**Comment by Yalagach** [comment]
Hi @debaraj-barua 

Thank you for helping me with the issue. I have made the changes and I request you to review it.

**Review by debaraj-barua — APPROVED** [review]
Looks Good 👍

**Comment by maribethb** [comment]
Nice, thank you @Yalagach for getting that signed! And thank you to @debaraj-barua for helping with amending the commits! This is ready to go, congrats on getting your PR merged!

**Comment by Yalagach** [comment]
Thank you @debaraj-barua and @maribethb

**Pull request merged**
