### PR TITLE
feat: add error callback to cross-tab copy-paste

### LINKED ISSUE #1218: Add error callback to the cross tab copy paste plugin
**Category**

 - Plugins

**Component**

cross-tab-copy-paste

**Is your feature request related to a problem? Please describe.**

There is the possibility that two unrelated projects could both have the cross tab copy paste plugin installed. This would allow people to try to paste blocks into a workspace where the definitions for those blocks do not exist (causing an error). External developers may want to handle those errors (e.g. presenting a message to the user when they happen). But currently this is not possible because there is no where for external developers to wrap the input event listeners in a `try... catch`.

**Describe the solution you'd like**

External developers should be able to pass a callback to the cross-tab-copy-paste plugin that is called when the plugin triggers an error when pasting.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by debaraj-barua**
fixes: #1218

### CODE REVIEW

**Comment by debaraj-barua** [comment]
Can someone please re-run the pipeline?

**Review by alschmiedt — COMMENTED** [review]
This looks good to me! Just one thing before I merge, would you mind updating the [README](https://github.com/google/blockly-samples/blob/master/plugins/cross-tab-copy-paste/README.md) to include an example of how you can use this new callback? I think you can just update the usage section.

**Comment by debaraj-barua** [comment]
@alschmiedt  Done, PTAL

**Review by alschmiedt — APPROVED** [review]
LGTM, thanks for picking up this issue! 🎊

**Pull request merged**
