### PR TITLE
chore: update backpack-demo to use JSON toolbox definitions instead of xml

### PR DESCRIPTION
**Pull request by nitesh-chowdhary**
chore(BLOCKLY-SAMPLES/examples/backpack-demo/index.js): change backpack-demo to use JSON toolbox

### CODE REVIEW

**Comment by gonfunko** [comment]
Thanks for the PR! I've prefixed the title with `chore:` to resolve the conventional commits check; it looks like you'll need to update the code some too to convert the toolbox definition to JSON. I posted some info about how to go about that [here](https://groups.google.com/g/blockly/c/S4G_AzFspfw) but let me know if you have any further questions.

**Review by nitesh-chowdhary — COMMENTED** [review]
refactor(BLOCKLY-SAMPLES/examples/backpack-demo/index.js): change backpack-demo to use JSON toolbox

**Comment by nitesh-chowdhary** [comment]
> Thanks for the PR! I've prefixed the title with `chore:` to resolve the conventional commits check; it looks like you'll need to update the code some too to convert the toolbox definition to JSON. I posted some info about how to go about that [here](https://groups.google.com/g/blockly/c/S4G_AzFspfw) but let me know if you have any further questions.

can you please write a PR comment so that my test case will pass
it's a humble request. This is my first contribution

**Comment by gonfunko** [comment]
> > Thanks for the PR! I've prefixed the title with `chore:` to resolve the conventional commits check; it looks like you'll need to update the code some too to convert the toolbox definition to JSON. I posted some info about how to go about that [here](https://groups.google.com/g/blockly/c/S4G_AzFspfw) but let me know if you have any further questions.
> 
> can you please write a PR comment so that my test case will pass it's a humble request. This is my first contribution

I'm not able to modify your commit message AFAIK, which seems to be necessary in addition to updating the title of the PR. If you run `git commit --amend`, you should be able to adjust the commit message (add the "chore: " prefix) and force push that. Also, feel free to ignore the conventional commit linter for now - we can worry about making it happy when your changes are finished.

**Comment by nitesh-chowdhary** [comment]
chore(BLOCKLY-SAMPLES/examples/backpack-demo/index.js): change backpack-demo to use JSON toolbox

**Comment by nitesh-chowdhary** [comment]
Updated examples/backpack-demo/index.js
Updated xml to JSON
Rewrite the toolbox

**Comment by nitesh-chowdhary** [comment]
I tried everything but nothing is happening

**Pull request closed without merging**
