### PR TITLE
Relaxed requirements on blocks with multiple generic inputs - project static

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Second to last PR for simple generic checks! And the last one is just tests for round-tripping though XML :D

This PR implements [Proposal A](https://docs.google.com/document/d/1QKYkmWjkle1JWCi3O8jXr8-7Toazh1pW_4EaVVgB_OI/edit#heading=h.z2m9hs1ghrwp) for multiple generic checks from the design document. The reason I decided to go with Proposal A is it means that the logic can be consistent when loading from XML (which connects blocks in order from leaves to roots).

Note that you should still be able to simulate Proposal B using the `bindType()` function provided by the connection checker =)

### Tests

* Connecting two blocks with sibling types to a generic parent.
* Explicitly binding the generic parent  to a supertype of the sibling types, then doing the same thing.
* Not allowing two unrelated types to connect to a generic parent.
* Explicit binding is given higher priority than parameter types.
* etc

I was also able to remove some of the `bindConnection` calls because of this change =)

### CODE REVIEW

**Comment by BeksOmega** [comment]
I think this PR may have gotten lost hehe. No rush if you guys are busy, just thought I'd bump it =)

**Review by rachel-fenichel — APPROVED** [review]
Whoops. Yes, this got lost in the rush. Approved, and I'll merge it.

**Comment by BeksOmega** [comment]
I don't know how github works so this might be a bit of a weird question. But like... would it be helpful if I requested reviews on things? I know you guys do it, but I don't even know where that information shows up haha.

I can't request reviews in the core repo, but I do have permissions here, so if that'd be helpful I'm happy to. Otherwise I'll just keep doing what I'm doing :D

**Comment by rachel-fenichel** [comment]
Our oncall person is generally responsible for triaging incoming pull requests and distributing them to people to review. Honestly, what happened here is just that I'm the only person with context to do this review, and I've been doing a lot of context-switching.

**Pull request merged**
