### PR TITLE
chore: convert xml to json for blocky webpack

### LINKED ISSUE #1254: Update blockly-webpack to use JSON toolbox definitions instead of xml
**Category**
 - Examples

**Component**

blockly-webpack

**Is your feature request related to a problem? Please describe.**

Many of the examples and plugins use XML toolboxes instead of the new JSON API. We should have our example code use the new APIs to best model what other developers can do with Blockly.

**Describe the solution you'd like**

Update the code in blockly-samples to use the JSON toolbox API.

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

1. Learn about [defining a toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) and read about the XML format vs the JSON format.
2. In blockly-samples, navigate to the blockly-webpack example's directory. Some examples can be started with `npm run start` and some can be opened directly by opening the `index.html` file in a browser. The README may give specific instructions, or you can look in the `package.json` to see what scripts are defined. Note you may need to run `npm install` in the example directory. Either way, open the example's demo page to observe the toolbox and its contents.
3. Write a new copy of the toolbox definition in the JSON format instead of the XML format. Where exactly it should be declared will depend on the example. It will most likely make sense to declare the toolbox definition close to the location where it is used, i.e. where `Blockly.inject` is called.
4. Refresh the demo page and make sure the toolbox looks the same as it did before. You can compare against the version in master on the [samples site](https://google.github.io/blockly-samples/) to make sure the behavior hasn't changed. Note that not all demos are published on the samples site so it may not be there.
5. Follow the rest of the instructions in the Contributing docs to verify your change and open a PR.

### PR DESCRIPTION
**Pull request by ritik307**
**Description**

- convert xml to json for blocky webpack

- Fixes #1254

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Hi @ritik307! The code looks good. Can you follow the instructions to sign the CLA so I can merge this?

**Comment by ritik307** [comment]
@rachel-fenichel i have signed the  cla/google and also rescanned the PR but still wasnt able to pass the check. Can you kindly look into this.

**Comment by BeksOmega** [comment]
Hello! Could you check the following two things for us real quick?

1) It's possible we don't have your GitHub username. Verify that [your existing CLA data](https://cla.developers.google.com/clas) is accurate.
2) You may not be using the email associated with your CLA in your Git commits. Check that the [email set on your git commits](https://help.github.com/articles/setting-your-email-in-git/) matches the [email associated with your CLA](https://cla.developers.google.com/clas).

If those are both correct then we will do some deeper digging =)

**Comment by ritik307** [comment]
@BeksOmega I have checked everything thoroughly as you have mentioned above but i am unable to find anything which i have submitted incorrectly.

**Comment by BeksOmega** [comment]
So I checked out your branch, and found your email. I've redacted the exact numbers and replaced them with X's to deal with email scrapers. It looks like: `ritikrawal@ip-XXX-XXX-X-XXX.ap-south-1.compute.internal`, is that the email you associated with your CLA?

**Pull request closed without merging**
