### PR TITLE
fix: update pitch field to es6 class

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Part of https://github.com/google/blockly-samples/issues/1267

Converts the pitch field example to an ES6 class with const and let. Mostly leaves the rest of the code in place.

### CODE REVIEW

**Comment by NeilFraser** [comment]
The only issue is with the Closure Compiler.  It doesn't support public class fields:
`field_pitch.js:33:2: ERROR - [JSC_LANGUAGE_FEATURE]`

I just moved the offending field to the bottom of the file, don't know if there's a better solution:
```
/**
 * All notes available for the picker.
 */
FieldPitch.NOTES = 'C3 D3 E3 F3 G3 A3 B3 C4 D4 E4 F4 G4 A4'.split(/ /);
```

**Comment by NeilFraser** [comment]
Also, change @return to @returns?

**Comment by rachel-fenichel** [comment]
I opened up the field in the demo page to test it and everything worked fine. Where is it being fed to Closure Compiler?

**Comment by NeilFraser** [comment]
> Where is it being fed to Closure Compiler?

In Blockly Games:
https://github.com/google/blockly-games/blob/master/appengine/music/src/field_pitch.js

**Comment by rachel-fenichel** [comment]
Since you've already applied fixes on the Blockly Games side, and since we're possibly getting rid of Closure Compiler there too, I think it's fine to leave the public fields in here. What do you think?

**Review by NeilFraser — APPROVED** [review]

**Pull request merged**
