### PR TITLE
feat: Update theme-dark to use JSON toolbox definitions instead of xml

### PR DESCRIPTION
**Pull request by Sharvari-t**
In this PR theme-dark plugin is modified to use JSON toolbox definitions instead of xml

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you so much @Sharvari-t !

**Review by alschmiedt — COMMENTED** [review]
Thank you for your PR! 

Now that we have the toolbox in JSON format, can you remove the xml toolbox definition found in the [index.html](https://github.com/google/blockly-samples/blob/48e115422f4d689a1d0b6169818e0247351ec83b/plugins/theme-dark/test/index.html#L26) file?

**Comment by alschmiedt** [comment]
Oops! Didn't see Bekas review : ) We can remove this in a different PR!

**Comment by Sharvari-t** [comment]
Thank you! This was a really fun session :D

**Comment by rachel-fenichel** [comment]
Thanks for contributing to Blockly, @Sharvari-t!

**Pull request merged**
