### PR TITLE
fix: unpkg import in Getting Started codelab for blockly v11

### LINKED ISSUE #2378: "Getting started" example won't run due to its unpkg import being invalid
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Getting Started codelab example code

### Description

Trying to run this in a browser gave multiple errors in the console due to `Blockly` being undefined. 

### Reproduction steps

1. Open the Getting Started example in a browser
2. Look at the browser console
3. Click "Edit" and then one of the colored blocks
4. See that no Blockly workspace is rendered

### Stack trace

```shell
TypeError: Cannot read properties of undefined (reading 'Msg')
    at blockly:8:55
    at blockly:10:2

ReferenceError: Blockly is not defined
    at sound_blocks.js:7:1

main.js:96 Uncaught ReferenceError: Blockly is not defined
    at main.js:96:3
    at main.js:102:3

main.js:25 Uncaught ReferenceError: Blockly is not defined
    at loadWorkspace (main.js:25:23)
    at HTMLDivElement.enableBlocklyMode (main.js:63:5)
```

### Screenshots

Screenshot 2024-05-28 at 2 20 24 PM

### PR DESCRIPTION
**Pull request by mark-friedman**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #2378

### Proposed Changes

Change the unpkg import to be valid.

### Reason for Changes

See #2378 for more info.

### Documentation

This PR updates the codelab documentation.

### CODE REVIEW

**Review by BeksOmega — COMMENTED** [review]
Hey Mark! Thanks for the fix :D

Could you actually change it to match the [usage we document on devsite](https://developers.google.com/blockly/guides/get-started/get-the-code#unpkg)?

```html
<!-- Load Blockly core -->
<script src="https://unpkg.com/blockly/blockly_compressed.js"></script>
<!-- Load the default blocks -->
<script src="https://unpkg.com/blockly/blocks_compressed.js"></script>
<!-- Load a generator -->
<script src="https://unpkg.com/blockly/javascript_compressed.js"></script>
<!-- Load a message file -->
<script src="https://unpkg.com/blockly/msg/en.js"></script>
```

Also @cpcallen just in case this wasn't expected to change.

**Comment by mark-friedman** [comment]
> Could you actually change it to match the [usage we document on devsite](https://developers.google.com/blockly/guides/get-started/get-the-code#unpkg)? ...

Sure.  I'll just point out that a few other examples also currently use "https://unpkg.com/blockly/blockly.min.js"

**Comment by mark-friedman** [comment]
@BeksOmega Do you want me to include the comments for those loads in the code and the codelab?

**Comment by BeksOmega** [comment]
> @BeksOmega Do you want me to include the comments for those loads in the code and the codelab?

Nah leaving them out is fine!

**Review by BeksOmega — APPROVED** [review]
Thanks again for the fix Mark!

**Pull request merged**
