### PR TITLE
chore: added new gh action to check for formatting upon every pr

### LINKED ISSUE #1977: Add a GitHub Action that runs the formatter
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

entire repo

### Problem

_No response_

### Request

After https://github.com/google/blockly-samples/pull/1946 is submitted, we'll have a new top-level script that can automatically format the entire repository. On every pull request, we should run `npm run format:check` which will run the formatter in a mode that reports if any file needs formatting still. We have a similar action in core blockly [here](https://github.com/google/blockly/blob/fd873507eba5c2e587bc2156398edc09e88b84d1/.github/workflows/build.yml#L70). We should add a similar job to our existing build/lint action in blockly-samples.

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sdthaker**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #1977 

### Proposed Changes

Added a Github action to `build.yml` file which essentially runs on the latest ubuntu and checks for code formatting automatically when a new PR is raised. It sets node to v20, installs all dependencies for the project and runs the command `npm run format:check` which in turn runs `prettier --check .` to check for code formatting for all the files in the project.

### CODE REVIEW

**Comment by BeksOmega** [comment]
@sdthaker Could you rebase this onto the latest master? We had an issue where our package locks got out of sync for a few private packages, but I think it should be resolved if you rebase.

**Comment by sdthaker** [comment]
> @sdthaker Could you rebase this onto the latest master? We had an issue where our package locks got out of sync for a few private packages, but I think it should be resolved if you rebase.

Sure! I’ll do that in a few of hours! Thanks!

**Comment by sdthaker** [comment]
> @sdthaker Could you rebase this onto the latest master? We had an issue where our package locks got out of sync for a few private packages, but I think it should be resolved if you rebase.

Sure! I’ll do that in a few of hours! Thanks!

**Comment by sdthaker** [comment]
Please let me know it this works, I rebased the branch against the master branch!

**Comment by BeksOmega** [comment]
Haha looks like this is good except for the formatting @sdthaker ! Can you run the formatter and then I'll get this merged?

**Comment by sdthaker** [comment]
> Haha looks like this is good except for the formatting @sdthaker ! Can you run the formatter and then I'll get this merged?

Done! =)

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you so much for the fix and the back and forth :D

**Pull request merged**
