### PR TITLE
fix : Removed incorrect statement about scrolling in demo serialize-disabled-interactions

### PR DESCRIPTION
**Pull request by HanaEason**
Addresses part of #1222

### CODE REVIEW

**Comment by BeksOmega** [comment]
HI @HanaEason After you sign the CLA put a comment here so I can rerun the check =) Then we can get your PR reviewed and merged!

**Comment by maribethb** [comment]
Hey there, thanks for the PR! Only a few steps left before we can merge!

1. You'll have to sign the CLA agreement (click the link the comment that google bot left)
2. Update the conventional-commits. Since there is only one commit, github will use the commit message and not the PR title, so the commit message has to follow the conventional-commit rules. you can follow these instructions to update it https://developers.google.com/blockly/guides/contribute/get-started/commits#fixing_non-conventional_commits (also note, there shouldn't be a space before the colon)
3. Add a PR description that says `fixes #1277` so this will be linked automatically to the issue!

**Review by BeksOmega — APPROVED** [review]
LGTM! Thank you for your fix Hana :D

**Comment by rachel-fenichel** [comment]
Thanks @HanaEason!

**Pull request merged**
