### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rachel-fenichel**

### CODE REVIEW

**Review by samelhusseini — APPROVED** [review]

**Comment by samelhusseini** [comment]
Will update https://github.com/google/blockly-samples/pull/189 to reflect this change.

**Comment by rachel-fenichel** [comment]
Should I just close this then?

**Comment by samelhusseini** [comment]
Sure.

**Comment by samelhusseini** [comment]
Updated https://github.com/google/blockly-samples/pull/189/commits/67a91a9be56c101b898fff859bb4e5477bec4b44

**Pull request closed without merging**
