### PR TITLE
fix(examples): remove date field in react demo

### LINKED ISSUE #2390: Remove date field from react demo
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

react demo in examples

### Problem

We're trying to reduce the number of cross-dependencies between examples and plugins to only those that actually demonstrate something useful The react demo uses the date field plugin but it already has an example of another field.

### Request

Delete the use of the date field in the react demo. There's no need to replace it with another field plugin.

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Saigenix**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #2390 

### Proposed Changes

Removed all code related to the date field plugin.

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This lgtm, thanks for the fixes @Saigenix =) Just going to wait for CI to pass before merging!

And just a note for the future, if you want to fix an issue, that is rad, but please comment on it asking to take it so that no one scoops it from under you!

**Comment by Saigenix** [comment]
> This lgtm, thanks for the fixes @Saigenix =) Just going to wait for CI to pass before merging!
> 
> And just a note for the future, if you want to fix an issue, that is rad, but please comment on it asking to take it so that no one scoops it from under you!

welcome and from now on I will comment on issue before working.

**Comment by BeksOmega** [comment]
@Saigenix could you run `npm run format` and push the changes? After that this should be good to go!

**Comment by Saigenix** [comment]
> @Saigenix could you run `npm run format` and push the changes? After that this should be good to go!

done!

**Comment by BeksOmega** [comment]
Thank you again for your fix! Let me know if you're interested in working on something else and need help finding a good issue =)

**Comment by Saigenix** [comment]
> Thank you again for your fix! Let me know if you're interested in working on something else and need help finding a good issue =)

Thanks for asking. Currently, I am enrolled in the Google Summer of Code, and my project is based on Blockly, so contributing to Blockly would be helpful for me

**Pull request merged**
