### PR TITLE
fix:enables strict mode for workspace_search

### LINKED ISSUE #2032: Enable strict mode for workspace-search
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-search

### Problem

_No response_

### Request

The workspace-search plugin does not have "[strict mode](https://www.typescriptlang.org/tsconfig#strict)" enabled for TypeScript. We should enable it to have better type checking for our plugins, but doing so may show some TypeScript errors that need to be fixed first.

This would be a good first issue for anyone experienced with working in TypeScript. You may need to adjust types, add checks for null or undefined, or make other fixes. If you have questions, feel free to ask here! In general, the team prefers avoiding casts and using `!` to coerce non-null types, and instead adding appropriate checks.

To work on this issue:

1. Run `npm install` at the root of Blockly samples to set up dependencies.
2. Navigate to the plugin's directory
1. Change `strict: false` to `strict: true` in the plugin's tsconfig.json
2. Run `npm run build` and see if there are any TypeScript errors.
3. Resolve any TypeScript errors, if present. If not, then we got lucky and accidentally wrote strict code! Yay!
4. Run `npm run build` again to make sure there are no TypeScript errors.
5. Run `npm run start` and play with the plugin in the playground to make sure the plugin still behaves as expected.
6. Run `npm run test` to run any automated tests.
7. Run `npm run lint` to make sure there are no formatting errors.
8. Open a PR with your changes!

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghoshvidip26**
## The basics

Enabling strict mode in workspace_search.ts

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #2032 

### Proposed Changes

I've enabled the strict mode for workspace_search.ts and there were some type after applying strict mode. So I've solved them by adding `!` where I got `Object is possibly null`

### CODE REVIEW

**Comment by BeksOmega** [comment]
Heya @Vidip-Ghosh It looks like your branch caught some unrelated changes to the continuous toolbox and content highlight. Could you remove those changes or open another PR without them?

**Comment by ghoshvidip26** [comment]
> Heya @Vidip-Ghosh It looks like your branch caught some unrelated changes to the continuous toolbox and content highlight. Could you remove those changes or open another PR without them?

I've removed those changes from my PR. Please check if its alright.

**Comment by BeksOmega** [comment]
> > Heya @Vidip-Ghosh It looks like your branch caught some unrelated changes to the continuous toolbox and content highlight. Could you remove those changes or open another PR without them?
> 
> I've removed those changes from my PR. Please check if its alright.

Hello! It looks like you've deleted the files, which is not what we're looking for :/ We want those files to be unchanged, because they're unrelated to this fix.

There are fancy ways to [undo changes with git](https://www.atlassian.com/git/tutorials/undoing-changes), but you might be better off starting a new branch and redoing your changes.

**Comment by ghoshvidip26** [comment]
> > > Heya @Vidip-Ghosh It looks like your branch caught some unrelated changes to the continuous toolbox and content highlight. Could you remove those changes or open another PR without them?
> > 
> > 
> > I've removed those changes from my PR. Please check if its alright.
> 
> Hello! It looks like you've deleted the files, which is not what we're looking for :/ We want those files to be unchanged, because they're unrelated to this fix.
> 
> There are fancy ways to [undo changes with git](https://www.atlassian.com/git/tutorials/undoing-changes), but you might be better off starting a new branch and redoing your changes.

Okay. I'll create a new branch & push all the changes.

**Comment by ghoshvidip26** [comment]
@BeksOmega Please review my PR #2054

**Pull request closed without merging**
