### PR TITLE
fix: Field Colour Plugin types

### LINKED ISSUE #1900: Publish types for field-colour
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-colour

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

### PR DESCRIPTION
**Pull request by mishra016**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

fixes https://github.com/google/blockly-samples/issues/1900

Fixes: Made change in the package-json -> "types": "./dist/index.d.ts",

### Proposed Changes

This Pull Request modifies the package.json file by updating the "types" field to "./dist/index.d.ts". This change is made to ensure that the type declarations for TypeScript are correctly exported.

### Reason for Changes

The reason for making this change is to provide proper TypeScript type declarations for the package. By specifying "./dist/index.d.ts" in the "types" field of package.json, TypeScript users can now benefit from improved type checking and autocompletion when using this package in their projects.

### Test Coverage

Since this change is related to the configuration of TypeScript type declarations, it does not directly impact the functionality of the code itself. Therefore, no unit tests are required for this specific change. It can be tested manually by verifying that TypeScript type checking works as expected when using the package in this project.

### Documentation

No additional documentation is required for this change, as it is a minor update to the package.json file that doesn't affect the usage of the package.

### Additional Information
This change is a simple but important enhancement for TypeScript users who rely on accurate type declarations when using the package. It will ensure a smoother development experience when working with the Blockly library in TypeScript projects.

### CODE REVIEW

**Comment by johnnesky** [comment]
I think the PR title needs a space after "fix:" to support conventionalcommits.org. Also please sign the CLA. Otherwise this looks great to me, thank you!

**Review by johnnesky — APPROVED** [review]

**Comment by mishra016** [comment]
Thank you for approving the changes!

**Comment by johnnesky** [comment]
Did you mean to close this issue?

**Comment by johnnesky** [comment]
Looks like everything is working now, thanks for the hard work!

**Pull request merged**
